USER_NICOLAS=nicolas
HOST_CHICAGO=192.168.50.102
HOST_NEW_YORK=192.168.50.103
HOST_LOS_ANGELES=192.168.50.104
PRIVATE_KEY_HOST_CHICAGO_USER_NICOLAS=~/.ssh/id_rsa_nicolas_Chicago
PRIVATE_KEY_HOST_NEW_YORK_USER_NICOLAS=~/.ssh/id_rsa_nicolas_NewYork
PRIVATE_KEY_HOST_LOS_ANGELES_USER_NICOLAS=~/.ssh/id_rsa_nicolas_LosAngeles

alias alias_SSH_connect_Local_Chicago='ssh -i $PRIVATE_KEY_HOST_CHICAGO_USER_NICOLAS $USER_NICOLAS@$HOST_CHICAGO'
alias alias_SSH_connect_Local_NewYork='ssh -i $PRIVATE_KEY_HOST_NEW_YORK_USER_NICOLAS $USER_NICOLAS@$HOST_NEW_YORK'
alias alias_SSH_connect_Local_LosAngeles='ssh -i $PRIVATE_KEY_HOST_LOS_ANGELES_USER_NICOLAS $USER_NICOLAS@$HOST_LOS_ANGELES'